services:
  escola-front-end:
    container_name: escola-front-end
    image: escola-front-end
    build:
      context: .
    ports:
      - "8585:8080"
    environment:
      - VUE_APP_API_URL=http://api-escola/api
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    restart: unless-stopped 
    working_dir: /app
    volumes:
      - ./:/app
      - /app/node_modules
    networks:
      - escola_network
    extra_hosts:
      - "api-escola:172.20.0.5"
networks:
  escola_network:
    driver: bridge